### ISSUE TITLE
If there's no wifi set in wpa_supplicant.conf, then completely skip the initial search

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway-wifi-setup#19]

**Comment by dhylands** [comment]
Just to clarify, this is talking about this "initial search" right?
https://github.com/mozilla-iot/gateway-wifi-setup/blob/628370ab6cf98c4e023434059b3e5576e7eed584/index.js#L27-L42

**Comment by andrenatal** [comment]
Yes
