### ISSUE TITLE
Use Case: I should be able to configure Wifi if the gateway can't connect to the internet.

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway-wifi-setup#23]
If I power up the gateway, and it's unable to connect to the internet (via Wifi or ethernet), then the device should go into AP mode so that I can configure a new Wifi connection.

It probably makes sense to allow the user to forcibly disable this feature (through a setting) from a security standpoint.

**Comment by dhylands** [comment]
I believe that the current software behaves this way, I just think that this should remain as a use case or user story.

**Comment by benfrancis** [comment]
This seems like a really bad idea from a security point of view. In a network outage can't anyone within range of the open WiFi access point connect to your gateway and reconfigure it?

This approach might be OK for something like Chromecast (which IIRC uses a PIN number on a visual display as an additional security mechanism), but it seems like an unacceptable risk for a smart home gateway.

**Comment by benfrancis** [comment]
This bug looks like a superset of #1
