### ISSUE TITLE
Raspberry stretch error

### ISSUE THREAD

**Issue by nfernandezsanz** [mozilla-iot/gateway-wifi-setup#70]
I followed al the steps in the readme. Finally , I succeded in running the programm . It enters in the AP mode("No WiFi found , entering AP mode")  , but no wifi appears.. then I  manually configure the WiFi credentials ,  but I am not able to have internet connection until I reboot the pi. Can anyone help me ? Thanks.

**Comment by dhylands** [comment]
Which readme were you following?

Is this installing the gateway onto an existing image of stretch?

The 0.5.0 and 0.5.1 releases are both based on stretch (You can download sdcard images from here:
https://github.com/mozilla-iot/gateway/releases
