### ISSUE TITLE
Running gateway.local issue

### ISSUE THREAD

**Issue by rlehman221** [mozilla-iot/gateway-wifi-setup#71]
After connecting the raspberry pi 3 to the new network created and then going to a web browser and typing in "gateway.local", nothing seems to load.

**Comment by hobinjk** [comment]
The "Mozilla IoT Gateway" network that the gateway-wifi-setup program creates is meant to be a captive portal network. For example, if you try to visit `http://detectportal.firefox.com/success.txt` while connected to that network it should redirect you to the wifi setup page. As far as I know gateway.local doesn't necessarily exist at that point in the process.

If this is happening after you connect the Pi to your local network then it's possible that your router is blocking mDNS traffic. What I would recommend in that case is to get your pi's assigned IP address from the router or from logging into your pi with a mouse and keyboard. You can then complete the rest of the first time setup using the local IP address.

**Comment by rlehman221** [comment]
This is happening before I connect the Pi to the local network. If I try to access http://detectportal.firefox.com/success.txt when the Pi is in AP mode nothing happens, the problem is that I'm not seeing that portal page for me to enter my network and password

**Comment by hobinjk** [comment]
Oh, hmm. That's strange. I was having a similar problem earlier today and fixed it by rebooting the Pi.

If that doesn't fix it, can you connect your Pi to a monitor and keyboard then attach the contents of the file `~/.mozilla-iot/logs/run-app.log`? Unfortunately that's the only way to get a good amount of debugging info.

**Comment by dhylands** [comment]
I just thought I'd point out that there are several ways to get the logging information. This page on the wiki covers the ways that I know about: https://github.com/mozilla-iot/wiki/wiki/Logging-into-the-Raspberry-Pi

**Comment by rlehman221** [comment]
ok I will try that then, also would it be a problem if I had ethernet connected while the Pi is in AP mode because that is what I have been doing

But just to confirm when I connect to the Pi what URL am I going to?

**Comment by dhylands** [comment]
I normally test with ethernet connected and often skip the wifi portion, and I haven't noticed any issues.

**Comment by rlehman221** [comment]
But what URL do you try to connect to, to access the portal online? I having been using gateway.local but wasn't sure if I had to replace gateway with something else

I also tried using the actual local IP address which is something like 10.0.1.190 for me

I also seem to be getting no errors

**Comment by benfrancis** [comment]
@hobinjk wrote:
> The "Mozilla IoT Gateway" network that the gateway-wifi-setup program creates is meant to be a captive portal network. For example, if you try to visit http://detectportal.firefox.com/success.txt while connected to that network it should redirect you to the wifi setup page. As far as I know gateway.local doesn't necessarily exist at that point in the process.

It should. If you have Ethernet connected and the gateway can get an IP address via DHCP then you should be able to access the gateway's web interface via gateway.local and skip the WiFi setup. Assuming we didn't break this during the gateway/wifi-setup merge?

@rlehman221 wrote:
> I also tried using the actual local IP address which is something like 10.0.1.190 for me

That should be working. Can your browser on the same network just not reach that IP? It sounds like the web server might not be running. Logs might help diagnose the cause.

**Comment by rlehman221** [comment]
I still haven't made any progress

I put logs in the files and it seems like the server is running along with the gateway but still nothing
