### ISSUE TITLE
Refused to Connect when trying to visit the ip address 192.168.220.1

### ISSUE THREAD

**Issue by eddieespinal** [mozilla-iot/gateway-wifi-setup#73]
I've followed every step in this document but I can't get it to display the wifi-setup page. I see my gateway network and I'm able to connect to it, but when I try to access the page to setup the wifi it says "192.168.220.1 refused to connect.".

Does anybody know what am I missing?

Thanks for your help.

Eddie.

**Comment by eddieespinal** [comment]
I figured it out.  Now sure how to make my raspberry pi to automatically take me to the port 8080.

But if anybody is stuck here too, just include the port number to the URL from the computer you are connecting to configure the wifi.

http://192.168.220.1:8080

That will automatically take you to http://192.168.220.1:8080/wifi-setup

I hope that helps anyone else.

**Comment by mrstegeman** [comment]
In our standard Raspberry Pi image, we set up iptables rules to do port redirection. See [here](https://github.com/mozilla-iot/gateway/blob/master/image/prepare-base.sh#L217).
