### ISSUE TITLE
Is this WiFi GW code used? 

### ISSUE THREAD

**Issue by pgupta408** [mozilla-iot/gateway-wifi-setup#74]
Hi,

I tested Gateway version 0.7 and the Gateway-0.7 does NOT match code in this repo. 

I want to create a WiFi AP + Gateway and want to try / modify this code . 

I know that router support is coming as part of GW release. If there is a development branch of Gateway that I can use then please advice.  I would rather use main-stream design and contribute if possible. 

Thanks

**Comment by mrstegeman** [comment]
It is used, but has been moved into the gateway itself: https://github.com/mozilla-iot/gateway/tree/master/src/wifi-setup

We have not started on the router/AP support yet, but will be doing so in the coming weeks on the master branch of the gateway.
