### ISSUE TITLE
Generate ssid for AP dynamically 

### ISSUE THREAD

**Issue by iamporus** [mozilla-iot/gateway-wifi-setup#78]
The server invokes `hostapd` service for starting the AP, which reads the ssid and other configurations from the `hostapd`.conf file (`/etc/hostapd/hostapd.conf` on Raspberry Pi).
This results in the same ssid for every AP running on multiple devices at my end. 

One solution I came across is at WebThings Gateway implementation. The ssid generated there is `WebThings_Gateway_XXXX`, where WebThings_Gateway is just the prefix and XXXX being a fragment of the device's mac address. This seems to be implemented in the WebThings Gateway source but not here in this repo. Any concerning developer can help shed some light on this. If the support is already added somewhere (in a different repo), please provide a link or reference to the same. I'm more than willing to take up the task myself to add the feature in this repo.

If not implemented anywhere, here's how I'd go about implementing it. 

1. `startAP()` inside `index.js` would see a parameter named `ssid_prefix`.
2. Inside wifi.js, where the implementation of `startAP()` is present, first create a file named `hostapd.conf` at `/etc/hostapd/` with the content being standard parameters required for AP and the ssid created using the provided prefix and device mac_address.
3. The actual creation of AP by invoking the system call.

For Edison, there would be a different approach.  
Please let me know your suggestions on the implementation part. Any pointers in the right direction are much appreciated.

**Comment by mrstegeman** [comment]
The code in this repository was merged into the gateway and has changed significantly. This code is no longer used directly.

The code you should be looking at lives here:
https://github.com/mozilla-iot/gateway/blob/master/src/wifi-setup.js

**Comment by iamporus** [comment]
Exactly what I needed. Thanks!
