### ISSUE TITLE
Blue screen  after choosing sub domain 

### ISSUE THREAD

**Issue by miko-code** [mozilla-iot/gateway-wifi-setup#79]
Im following   the getting started guide 
After part 5 "chose the sub domain" i got  redirected  successfully  to the new  sub domain.
Then i got stuck on a blue screen .
debugging  i can see that there   is 2 errors.

`Uncaught SyntaxError: Unexpected token (`

**Comment by dhylands** [comment]
This particular repository is now obsolete. The wifi setup has been merged into the main gateway repository.
See: https://github.com/mozilla-iot/gateway/blob/master/src/wifi-setup.js

Would it be possible to get a filename and line number of where the error is being encountered? Which version of the gateway are you using?
