### ISSUE TITLE
Rpi Zero W wifi does not start

### ISSUE THREAD

**Issue by Whoweez** [mozilla-iot/gateway-wifi-setup#80]
Hi there :)

Thanks a lot for this library!

I'm trying to run this on Raspberry Pi Zero W and the wifi doesn't want to startup:

## When running: 
`sudo systemctl start mozilla-gateway-wifi-setup`

## and then 
`sudo journalctl -u mozilla-gateway-wifi-setup`

## This is the output:
`Jun 25 19:28:09 raspberrypi run.sh[16862]: /home/pi/gateway-wifi-setup/run.sh: line 17: cd: /root/gateway-wifi-setup: No such file or directory`

## When I go to node directory and run:
`sudo node index.js`

## Then I get this:

```
starting the wifi server
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
HTTP server listening
Running command: wpa_cli -iwlan0 list_networks
List Networks command executed: network id / ssid / bssid / flags
0	myWIFI	any	[CURRENT]
check 1
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
COMPLETED
WiFi connection found. resolving
resolved
start the gateway
Running command: systemctl start mozilla-iot-gateway
stop wifi setup
Running command: systemctl stop mozilla-gateway-wifi-setup
Error running command: { [Error: Command failed: /bin/sh -c systemctl start mozilla-iot-gateway
Failed to start mozilla-iot-gateway.service: Unit mozilla-iot-gateway.service not found.
]
  killed: false,
  code: 5,
  signal: null,
  cmd: '/bin/sh -c systemctl start mozilla-iot-gateway' }
Error starting Gateway: { [Error: Command failed: /bin/sh -c systemctl start mozilla-iot-gateway
Failed to start mozilla-iot-gateway.service: Unit mozilla-iot-gateway.service not found.
]
  killed: false,
  code: 5,
  signal: null,
  cmd: '/bin/sh -c systemctl start mozilla-iot-gateway' }
VWifi service stopped
```

I'm not sure why it is not taking on?

Any suggestions for troubleshoot would be appreciated.

Kind Regards :)

**Comment by mrstegeman** [comment]
This repo is no longer used. The Wi-Fi setup is now integrated with the gateway itself, so there is no longer a separate systemd service.
